// Actions
export const ACCESS_ADD_REQUEST = 'ACCESS_ADD_REQUEST';
export const ACCESS_ADD_SUCCESS = 'ACCESS_ADD_SUCCESS';
export const ACCESS_ADD_FAIL = 'ACCESS_ADD_FAIL';

// Messages
export const ACCESS_EMPTY_SUCCESS = 'ACCESS_EMPTY_SUCCESS';
export const ACCESS_EMPTY_ERROR = 'ACCESS_EMPTY_ERROR';
