export const CART_PRE_ADD_ITEM = 'CART_PRE_ADD_ITEM';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const ITEM_ALREADY_IN_CART = 'ITEM_ALREADY_IN_CART';
