export const PACKET_LIST_REQUEST = 'PACKET_LIST_REQUEST';
export const PACKET_LIST_SUCCESS = 'PACKET_LIST_SUCCESS';
export const PACKET_LIST_FAIL = 'PACKET_LIST_FAIL';

export const PACKET_DETAILS_REQUEST = 'PACKET_DETAILS_REQUEST';
export const PACKET_DETAILS_SUCCESS = 'PACKET_DETAILS_SUCCESS';
export const PACKET_DETAILS_FAIL = 'PACKET_DETAILS_FAIL';

export const PRE_PACKET_DETAILS_REQUEST = 'PRE_PACKET_DETAILS_REQUEST';
