export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST';
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS';
export const REVIEW_CREATE_FAIL = 'REVIEW_CREATE_FAIL';
export const REVIEW_CREATE_RESET = 'REVIEW_CREATE_RESET';

export const REVIEW_CREATE_EMPTY_ERROR = 'REVIEW_CREATE_EMPTY_ERROR';
export const REVIEW_CREATE_EMPTY_SUCCESS = 'REVIEW_CREATE_EMPTY_SUCCESS';
